### ISSUE TITLE
给个建议，增加两个回调

### ISSUE THREAD

**Issue by maltsugar** [jasnig/ZJScrollPageView#1]
建议增加 1回调已经选中某个标签的viewController（模仿系统的tabbar， didSelectViewChontroller）
2. 滑动到某个viewController的回调

因为，现在有个需求：4个vc公用某一个状态view， 但是会根据对应的VC更新状态。现在尝试自己增加这样的回调

**Comment by jasnig** [comment]
@maltsugar 朋友, 这两个回掉的问题我之前想到过, 但是其实不用使用回掉也能达到你们的需求, 因为每个界面是子控制器, 所以出现的时候是会调用viewWillAppear之类的生命周期方法, 你可以在里面根据不同的title(建议在初始化ScrollPageController的子控制器的时候将他的标题设置为和滑块上对应的标题一样)调整显示不同的内容, 我目前就是这样使用的, 不过倒是可以发布一个通知出来

**Comment by jasnig** [comment]
@maltsugar 朋友, 已经增加了一个通知"ScrollPageViewDidShowThePageNotification"可以监听到显示的index, 你可以看看#import "ZJSegmentStyle.h" 里面的使用说明, 多谢提这个建议

**Comment by maltsugar** [comment]
恩 我自己也在你的代码里加了回调
