### ISSUE TITLE
首次进入 第一个childVc的viewWillAppear不调用

### ISSUE THREAD

**Issue by zhangli4659507** [jasnig/ZJScrollPageView#11]
首次进入 第一个childVc的viewWillAppear不调用

**Comment by jasnig** [comment]
@zhangli4659507 朋友, 如果你仔细阅读readme文件, 你会发现里面就这个问题有过解释, 和解决方法, 另一方面其实我在使用的时候甚至都不需要用到生命周期方法和子控制器的代理方法, 直接在父控制器的代理方法里面就能够完成子控制器需要的操作

**Comment by iShawnWang** [comment]
还是感觉有些奇怪, 如果用了 [ViewController Containment Api](https://objccn.io/issue-1-4/) ,那么子控制器的生命周期方法应该会正常调用的 ~,
为什么要说 `但是注意ZJScrollPageView不会保证viewWillAppear等生命周期方法一定会调用`

**Comment by jasnig** [comment]
@iShawnWang 朋友, 如果你详细去看过相关的文档, 会发现文档中会有说明, 要保证容器中的控制器的生命周期被正常的调用, 是需要在适合的地方手动的调用beginAppearanceTransition:animated:和endAppearanceTransition这些方法的
