### ISSUE TITLE
如果我点击n+2个，n+1个会被触发

### ISSUE THREAD

**Issue by wonin5** [jasnig/ZJScrollPageView#13]
RT，这算bug吧？作者可以验证一下

**Comment by jasnig** [comment]
@wonin5 你好, 这个是内部处理了, 会触发加载附近的一两个页面, 不过页面也只是加载一次

**Comment by wonin5** [comment]
是animatedContentViewWhenTitleClicked = NO;对吗？我把mjrefresh添加到子view对应的头部，当我点击第n+2个，第n+1个已经被触发，其他都没问题。

**Comment by jasnig** [comment]
@wonin5 嗯是的, 你可以试试, 然后最近我应该会再次修改一下它

**Comment by wonin5** [comment]
我特意给每个控制器加了刷新，点击第n+2个，第n+1个还是会被触发，还有个问题大神，我设置导航栏为透明也是无效的，求验证

**Comment by ygsky** [comment]
也发现了同样的问题。。会触发相近的两个。有时候页面直接就空白了。。

**Comment by jasnig** [comment]
@ygsky @wonin5 已更改一些地方,可以试试看是否解决

**Comment by jasnig** [comment]
@wonin5 导航栏的相关处理要使用
 self.zj_scrollViewController.navi... 来处理

**Comment by zhangyanglin** [comment]
这个问题还是存在 快速滑动时   会触发后面的一个vc
