### ISSUE TITLE
当左右滑动处于最后一个Tab时，如果这时再向左滑动，会数组越界crash

### ISSUE THREAD

**Issue by 405092901** [jasnig/ZJScrollPageView#16]
当左右滑动处于最后一个Tab时，如果这时再向左滑动，会数组越界crash，如下图
![2016-10-09 16 00 32](https://cloud.githubusercontent.com/assets/21153664/19218970/ea1f11a8-8e39-11e6-8544-17435ebb1d7b.png)
![2016-10-09 16 01 17](https://cloud.githubusercontent.com/assets/21153664/19218972/f59cf6f8-8e39-11e6-8a1a-80e732102f5d.png)

**Comment by jasnig** [comment]
@405092901 朋友, 这个问题已经更新过了, 你试试最新的吧

**Comment by 405092901** [comment]
用的是0.2.0版本，你可以修改你的demo中的ZJVc6Controller类，把数据源从2个，添加多一些，比如8个（再调大一些segment的长度比如280，方便滑动），这样就可以复现了。

**Comment by jasnig** [comment]
@405092901 下载源码使用吧, cocoaPods上面很久没有更新过了

**Comment by 405092901** [comment]
- -! 我就是下载通过下载的源码demo，出现的crash
![2016-10-10 17 33 28](https://cloud.githubusercontent.com/assets/21153664/19231989/c9825b5e-8f0f-11e6-8f61-552fa55896e6.png)

**Comment by jasnig** [comment]
@405092901  但是你上面最开始的代码截图已经是很久之前版本里面的代码了, 最新的代码里面不是那样的

**Comment by zhangyanglin** [comment]
确实会数组越界 快速两个页面滑动时

**Comment by keluokeda** [comment]
在边界 继续 频繁 快速滑动 会数组越界

**Comment by keluokeda** [comment]
@jasnig  能把cocoaPods更新一下吗

**Comment by jasnig** [comment]
@keluokeda @zhangyanglin抱歉之前最近更新的时候产生了bug, 刚刚处理了, 可以看看是否解决,  我的电脑最近cocoaPods连接不上
