### ISSUE TITLE
ios 10  isFirstTime 失效

### ISSUE THREAD

**Issue by wangyuuuu** [jasnig/ZJScrollPageView#22]
- (void)setUpWhenViewWillAppearForTitle:(NSString *)title forIndex:(NSInteger)index firstTimeAppear:(BOOL)isFirstTime {
}

希望作者及时更新。万分感谢。

**Comment by jasnig** [comment]
@wangyuuuu 朋友, 在iOS10中UICollectionView的生命周期方法的调用时机已经和之前的不一样了, 所以会失效了, 另外, 这个最近的更新已经放弃了之前的代理方法, 你可以试下最新的, 给你带来不便很抱歉, 如果你在切换使用新代码过程中遇到问题, 请联系我

**Comment by jasnig** [comment]
@wangyuuuu 朋友, 在iOS10中UICollectionView的生命周期方法的调用时机已经和之前的不一样了, 所以会失效了, 另外, 这个最近的更新已经放弃了之前的代理方法, 你可以试下最新的, 给你带来不便很抱歉, 如果你在切换使用新代码过程中遇到问题, 请联系我

**Comment by jasnig** [comment]
@wangyuuuu 朋友, 在iOS10中UICollectionView的生命周期方法的调用时机已经和之前的不一样了, 所以会失效了, 另外, 这个最近的更新已经放弃了之前的代理方法, 你可以试下最新的, 给你带来不便很抱歉, 如果你在切换使用新代码过程中遇到问题, 请联系我
