### ISSUE TITLE
在第一个按钮处  来回滑动  按钮会 卡死   然后就点不动 了

### ISSUE THREAD

**Issue by SwiftBMan** [jasnig/ZJScrollPageView#3]

**Comment by SwiftBMan** [comment]
在第一个按钮处 来回滑动 按钮会 卡死 然后就点不动 了

**Comment by jasnig** [comment]
@SwiftBMan 对的, 这个来回滚动的速度很快的时候是有这个问题的, 一直没有时间来解决这个问题, 不过确实有些人就是喜欢来回快速滚动玩, 这个问题需要解决, 欢迎P-R

**Comment by jasnig** [comment]
@SwiftBMan already be fixed, thanks for your sugguetion

**Comment by SwiftBMan** [comment]
还有个bug 需要解决    来回滑动  不松手(还是第一个按钮）      滑动条会卡在那   虽然松手后会复位   但感觉不太好  希望解决（>> <<).

**Comment by jasnig** [comment]
@SwiftBMan  ok! already be fixed!
