### ISSUE TITLE
如何改变整个控件的颜色

### ISSUE THREAD

**Issue by jianjianhao** [jasnig/ZJScrollPageView#7]
我想整个控件颜色可以改变怎么修改

**Comment by jasnig** [comment]
@jianjianhao 什么整个控件的颜色

**Comment by jasnig** [comment]
@jianjianhao 请下载最新的代码  ,,,,,     
  // 这里可以设置头部视图的属性(背景色, 圆角, 背景图片...)
    scrollPageView.segmentView.backgroundColor = [UIColor blackColor];
